FROM ubuntu

RUN apt-get update -y

RUN apt-get install openjdk-8-jdk wget -y

WORKDIR /opt

RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz.asc

RUN tar -xvzf apache-tomcat-9.0.89.tar.gz

RUN mv apache-tomcat-9.0.89 tomcat

COPY target/welcomeapp.war /opt/tomcat/webapps/

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh","RUN"]